### ISSUE TITLE
Q: Is there a way to handle SIGSYS/ActTrap in go code?

### ISSUE THREAD

**Issue by yvesf** [seccomp/libseccomp-golang#54] opened 2020-08-11 16:02 UTC
It seems currently it's not possible to handle the signal by `ActTrap` seccomp action in go.

As the kernel sets  si_code to SYS_SECCOMP (=1), go will dispatch the signal to `signal.Notify` if it is set to SI_USER (=0). (see runtime/signal_unix.go in sighandler(), SIGSYS is also not flagged as Notify in sigtab_linux_generic.c).

I created a small demo where I also can override `siginfo.si_code` to 0. In that case Go dispatches the signal but the unfortunate side-effect is that the caller of the syscall is then no longer blocked and returns. I don't know how to prevent that and still it's an ugly hack. https://gist.github.com/yvesf/aa72d055cdaefa25a976ed2a7f86ef3b

What if I want to act on the SIGSYS, for example exit with a certain exit-code or communicate something special to stdout instead of immediately getting the crash traceback?

Thanks for suggestions!

**Comment by pcmoore** [comment] 2020-08-12 00:40
Hi @yvesf, I don't have an answer for you right now, but @drakenclimber and myself will be spending a bit more time with the libseccomp golang bindings in the near future; hopefully we will be able to answer your question better at that point in time.

If you do find a better answer, please let us know!

**Comment by drakenclimber** [comment] 2021-01-25 20:10
I looked into this issue a little bit this morning.

>  I created a small demo where I also can override siginfo.si_code to 0.

I agree, the `info->si_code = 0;` [line](https://gist.github.com/yvesf/aa72d055cdaefa25a976ed2a7f86ef3b#file-main-go-L16) really stinks, but that seems like a golang issue and not a seccomp or seccomp-golang issue.

> In that case Go dispatches the signal but the unfortunate side-effect is that the caller of the syscall is then no longer blocked and returns. I don't know how to prevent that and still it's an ugly hack.

For me anyway, the actual signal handler itself behaved just as it would in C.  I didn't experience the nonblocking behavior you outlined above.

With this handler, here's what I saw:
```
static void mySigHandler(int signum, siginfo_t *info, void *context) {
        fprintf(stderr, "received of SIGSYS. si_syscall=%d\n", info->si_syscall);
        fflush(stderr);

        info->si_code = 0;
        sleep(10);
        exit(5);
}
```
```
$ ./traptest 
received of SIGSYS. si_syscall=260
<as requested, there was a 10-second delay before the console returned>
```


In the following case, I commented out the `exit()`.  Just like in C, the signal was handled - poorly I might add :) - and the main program continued to run after the handler completed.  I didn't see any strange nonblocking behavior here.

```
static void mySigHandler(int signum, siginfo_t *info, void *context) {
        fprintf(stderr, "received of SIGSYS. si_syscall=%d\n", info->si_syscall);
        fflush(stderr);

        info->si_code = 0;
        sleep(10);
        //exit(5);
}
```
```
$ ./traptest 
received of SIGSYS. si_syscall=260
<there was a 10-second delay before the following line printed>
should never reach me
```

**Comment by kolyshkin** [comment] 2021-10-29 22:23
@drakenclimber @yvesf so, should this be closed as we're unable to reproduce it?

**Comment by drakenclimber** [comment] 2021-11-30 22:53
> @drakenclimber @yvesf so, should this be closed as we're unable to reproduce it?

Yes, I believe so.  @yvesf, feel free to reopen this issue if new information is available.  Thanks, all.

**Closed by drakenclimber** 2021-11-30 22:53 UTC
Labels: question
